cc-foet/Code-Satra

Shikhar/README.md
This folder will serve as the place to store my code for the solution of the problems during the code-satra coding challenge.
=> Added Readme to my folder

Mayank-Gupta/README.md
=> Made Readme

Raunak-Kaushal/Day1challenge.c, Raunak-Kaushal/README.md
=> This is my first contribution.

Mohammad-Abbas/Day1.cpp
Intution:
The problem is basically solved with Bubble Sort Algorithm and Swap can be count by taking a variable like count and initialise it with 0 int count=0; and incrementing it in a second loop where actually swapping take place and then print it out at last .
Thank You !
=> Solve Day1 Problem

Lazeena Iftekhar/README.md, Lazeena Iftekhar/twoSumII_Day1.java
=> Add Solution for twoSumII

Lazeena Iftekhar/DayOne.java
=> Added Solution for Day 1 Problem

Arindam Shukla/.vscode/settings.json, Arindam Shukla/Day_1_question.cpp
=> day 1 solution Arindam Shukla

Saif/Day2-Probelm-Leetcode-3.md
Solve leetcode problem number 3 'Longest substring'
=> Frist question of day-2

Farhan/3sum.cpp
=> Add solution for Integer Triplets

Asmi Bhaskar/day2 sorting using merge sort.c
=> merge sort using c day 2

Somesh Pratap Singh/MergeSort.java
Given an array of n+m elements where n elements are sorted . Your task is to sort last m elements in place such that array became sorted.  Using Merge sort .
=> Day2.MergeSort.java

Ratnesh-Shukla/MergeSort.c++
=> Merge Sort

Arindam Shukla/Day_2_question.cpp
solution for the day 2  question
=>  day 2 solution

Asmi Bhaskar/day 3 searching.c
used binary search and standard Boolean library for true and false flag
=> Day 3 problem searching

Venkatesh/Searching/Searching.c, Venkatesh/Searching/Searching.java, Venkatesh/Searching/Searching.py
=> Day3 Commit

Farhan/Merge_Sort.cpp
=> Sort the Unsorted Part Of Array

Vishal bist/Occurrence.cpp
=> Day 3: Program to check the first and last occurrence of an element in a sorted array

Prachi-Yadav/D1_BubbleSort.c, Prachi-Yadav/readme.md
Added `BubbleSort` function in `D1_BubbleSort.c` to perform sorting using the Bubble Sort algorithm.
=> Solution of day 1 problem

Venkatesh/Greedy-Lemonade/Lemonade.c, Venkatesh/Greedy-Lemonade/Lemonade.java, Venkatesh/Greedy-Lemonade/Lemonade.py
=> Day4 commit

Asmi Bhaskar/day 4 lemonade problem.c
used stdbool for the true and false
=> day 4 lemonade problem

Vikas Saroj/Day 3/bouquets.py
Question: To make one bouquet we need K adjacent flowers from the garden. Here the garden consists of N different flowers, the ith flower will bloom in the bloomDay[i]. Each flower can be used inside only one bouquets. We have to find the minimum number of days need to wait to make M bouquets from the garden. If we cannot make M bouquets, then < return -1.
=> solved Day3 problem

Mohammad-Abbas/Day4.cpp
Day 4 Problem Solved 
Problem Approach : 
Based on Greedy Algorithm
=> Day 4 Problem Solved

Venkatesh/Divide-And-Conquer/Merge.c, Venkatesh/Divide-And-Conquer/Merge.java, Venkatesh/Divide-And-Conquer/Merge.py
did divide and conquer algorithm
=> Day5 commit

Asmi Bhaskar/DSA with Python (PYTHON BELYAT)/passing the pillow.py
PYTHON BEELYAT!
leetcode problem number 2582
with a time optimized and non optimized solution
=> passing the pillow.

Ayush Singh/Day6.java
On removing duplicates from a sorted linked list 
Used Java LinkedLists
=> Add Day6 Problem

Mohammad-Abbas/Day6.cpp
Question is easy :
1)Create Linked List 
2)Traverse and Print LL
3) Remove Duplicates by using delete
=> Day6 Problem Solved

Farhan/Kth_element.cpp, Farhan/LL_Duplicacy.cpp
Removing Duplicacy was really a tricky yet useful one. 
This would help in Reducing data redundancy and maintain data integrity in my future projects
=> Day 5 and Day 6 Solutions 

Vishal bist/Search_element.cpp
…ray (not necessarily with distinct values).
=> Day 6: Program to check if the given number is present in a sorted array (not necessarily with distinct values).

Saif/Day-7-CC Problem.md
Check if the string is palindrome or not using stack and queue
=> Day-7 CC-Problem

Asmi Bhaskar/day 6 linked list problem.c, Asmi Bhaskar/day 7 cc problem.c
use of std library for the creation of dynamic data structures along with sting library for ch and other data types. in c
=> (day 7) 6th and 7th day cc problem in c

Farhan/Palindrome_Check.cpp
Great Piece of problem using stacks and queues and their opposite properties to check palindrome was really something good to learn
=> Solution to checking palindrome string using Stack and Queue

Mohammad-Abbas/Day7.cpp
Day 7 Problem solved :
Approach :
In stack create a stack push string character in it and then pop out each and compare with string element
In queue create a queue and push all element from queue to reversestr and then check if the string is same or not with given string .
=> Day7 Problem

Farhan/div_subarray_2pointer.cpp, Farhan/divisible_subarray.cpp
Using Hashing may not be the most optimal solution to this problem if we're not considering positives and negatives of the number given and taking it unsigned(Because the question didn't mention so). Optimal way to solve this is using 2 pointers.Given both of the solutions in this commit
=> 2pointer and Hashing Solution of the longest Subarray divisible by K

Venkatesh/2D-Array/Matrix.c, Venkatesh/2D-Array/Matrix.java, Venkatesh/2D-Array/Matrix.py, Venkatesh/2D-Array/README.md
=> Day9 commit

Asmi Bhaskar/day 9 cc problem.c
spiral index matrix approach in c
=> cc problem day 9 

Venkatesh/Binary-Tree/Tree.c, Venkatesh/Binary-Tree/Tree.java, Venkatesh/Binary-Tree/Tree.py
did no of binary tree from given inorder traversal
=> Day10 commit

Vishal bist/Minimum_page_allocation.cpp
…d according to the given instructions
=> Day 10: Program to find the minimum number of pages that can be allocated according to the given instructions.

Venkatesh/Binary-Search-Tree/BST.c, Venkatesh/Binary-Search-Tree/BST.java, Venkatesh/Binary-Search-Tree/BST.py
did sorted linked list to bst preorder
=> Day11 commit

Asmi Bhaskar/day 12 heap problem.c
uses limit library which contains int_max which indicates that the array is exhausted and don't have anymore elements to contribute
=> Create day 12 heap problem.c

Venkatesh/Heap/MergeHeap.c, Venkatesh/Heap/MergeHeap.java, Venkatesh/Heap/MergeHeap.py
did merging arrays using min heap
=> Day12 commit

Mohammad-Abbas/Day13.cpp
=> Solved Day13

Venkatesh/Graph/Cyclic.c, Venkatesh/Graph/Cyclic.java, Venkatesh/Graph/Cyclic.py
=> Day15 commit

.gitignore, Vishal bist/Magnetic_force_between_two_balls.cpp
=> Day 15: Program to find the maximum distance and minimum magnetic force between two balls.

Vishal bist/Longest_alternating_subsequence.cpp
=> Day 16: Program to find the length of the longest alternating subsequence.

Venkatesh/Dijkstra/Path.c, Venkatesh/Dijkstra/Path.java, Venkatesh/Dijkstra/Path.py
did shortest path using Dijkstra's Algorithm
=> Day17 commit

Venkatesh/Floyd-Warshall/PairPath.c, Venkatesh/Floyd-Warshall/PairPath.java, Venkatesh/Floyd-Warshall/PairPath.py
did shortest path b/w every pair using Floyd-Warshall algorithm
=> Day18 commit

Venkatesh/Bellman-Ford/Path.c, Venkatesh/Bellman-Ford/Path.java, Venkatesh/Bellman-Ford/Path.py
did shortest path using Bellman-Ford algorithm
=> Day19 commit

Asmi Bhaskar/day 19.c
Bellman-Ford algorithm implemented in C
=> Create day 19.c

Venkatesh/Dynamic-Programming/Painter.c, Venkatesh/Dynamic-Programming/Painter.java, Venkatesh/Dynamic-Programming/Painter.py
=> Day20 commit

Venkatesh/Knapsack/Coins.c, Venkatesh/Knapsack/Coins.java, Venkatesh/Knapsack/Coins.py
=> Day21 commit

Venkatesh/Longest-Common-Subsequence/LongestSubsequence.c, Venkatesh/Longest-Common-Subsequence/LongestSubsequence.java, Venkatesh/Longest-Common-Subsequence/LongestSubsequence.py
=> Day22 commit

Venkatesh/Backtracking/NQueens.c, Venkatesh/Backtracking/NQueens.java, Venkatesh/Backtracking/NQueens.py
=> Day23 commit

Venkatesh/Topological-Sorting/Dependencies.c, Venkatesh/Topological-Sorting/Dependencies.java, Venkatesh/Topological-Sorting/Dependencies.py
=> Day25 commit

Venkatesh/Disjoint-Set-Union/ComputerNetwork.c, Venkatesh/Disjoint-Set-Union/ComputerNetwork.java, Venkatesh/Disjoint-Set-Union/ComputerNetwork.py
did query in network using disjoint set union
=> Day26 commit

Venkatesh/Trie/Autocomplete.c, Venkatesh/Trie/Autocomplete.java, Venkatesh/Trie/Autocomplete.py
did autocomplete with trie data structure
=> Day27 commit

Mohammad-Abbas/Day27.cpp
=> Solved today POTD

Venkatesh/Segment-Tree/Increments.c, Venkatesh/Segment-Tree/Increments.java, Venkatesh/Segment-Tree/Increments.py
did increments problem with segment tree
=> Day28 commit

Vishal bist/Longest_substring.cpp
=> Day 28: Program to find length of the longest unique substring.

Venkatesh/Fenwick-Tree/InversionCount.c, Venkatesh/Fenwick-Tree/InversionCount.java, Venkatesh/Fenwick-Tree/InversionCount.py
=> Day29 commit

Venkatesh/Advance-Graph/Kruskal/MinSpanTree.c, Venkatesh/Advance-Graph/Kruskal/MinSpanTree.java, Venkatesh/Advance-Graph/Kruskal/MinSpanTree.py, Venkatesh/Advance-Graph/Prim/MinimumSpanTree.c, Venkatesh/Advance-Graph/Prim/MinimumSpanTree.java, Venkatesh/Advance-Graph/Prim/MinimumSpanTree.py
did MST with both kruskal and prim
=> Day30 commit
